FirelyTeam/firely-docs-firely-server

releasenotes/releasenotes.rst, tools/firely-server-import.rst
=> VONK-3042: added documentation for MongoDB support in FSI

releasenotes/releasenotes.rst
- Add note for fixing PATCH in the context of SoF
- Add note for supporting Inferno v2.2.1
=> Updated release note

getting_started.rst, reference/programming_api/repository.rst, releasenotes/releasenotes_v3.rst
=> Fixed typos

facade/databasemodel.rst
latest EF version is 7.0.0, while Firely server uses EF 3.1.14.
=> clarified EF version in note

releasenotes/releasenotes.rst, releasenotes/releasenotes_v4.rst, releasenotes/releasenotes_v5.rst, security/auditing.rst
... and a small fix for a build error that found its way into the documentation 🙂
=> Feature: Add FS 5.0.0 release notes

reference/architecture.rst
Tried to rebase my previous pull request, got lost in the web of git rebase commands. Decided it was better to checkout develop 5.0, add my changes there, and make a new pull request. I hope this works.
=> added extra info capstatement

releasenotes/releasenotes_v5.rst, security/permissions.rst
I opted to copy and extend the FS 5.0.0-beta1 release notes, otherwise it would get mighty confusing for readers.
=> VONK-4430: FS 5.0.0 release notes

features_and_tools/bulkdataexport.rst, features_and_tools/firely-server-ingest.rst, getting_started/binary.rst, overview.rst, security/firely-auth/firely-auth-tutorial.rst, security/firely-auth/firely-auth.rst, setting_up_firely_server/configuration/appsettings.rst, setting_up_firely_server/deployment/helm.rst
Following changes were made:
deployment>helm chart: Changed  identity server => firely auth
BDE: Added  infobox to BDE stating it is a licensed feature
FSI: Added  infobox to FSI stating it is a licensed feature
Basic Installation: added infobox stating that FS runs on all platforms that support .net
Firely Auth: added link to download zip https://downloads.simplifier.net/firely-auth/firely-auth-latest.zip, added infobox stating it is a licensed feature.
Firely Server Settings: Adjusted this page to be up to date with the current situation (may need more explanation for certain parts)
Overview: Added Yannicks comments on overview page.
=> Added agreed changes

reference/programming_api/repository.rst
IResourceChangeRepository.EnsureMeta seems to be replaced by IResource.EnsureMeta().
=> EnsureMeta fix for IResourceChangeRepository

compliance/us_core.rst
=> Update us_core.rst to latest postman

features_and_tools/customresources.rst, setting_up_firely_server/deployment/docker.rst
Added information on loading conformance resources in docker, removed information on the possibility to add custom search parameters on custom resources as we currently do not support this.
=> Added info on loading conformance res. in docker

setting_up_firely_server/configuration/logsettings.rst
Added information on setting the CorrelationId and making logs on individual requests visible
=> added section on CorrId/log indvdl requests

releasenotes/releasenotes_v5.rst
Added link to FS download site, is this ok?
=> added reference to Upgrade/binaries/docker

security/firely-auth/firely-auth-deploy.rst
Please check if this is clear and correct, I may not have a complete understanding and describe things the wrong way.
=> Added information on FA/FS in docker

features_and_tools/firely-server-ingest.rst
Merge hotfix release notes back into develop branch.
=> Hotfix/fsi v2.2.1

features_and_tools/firely-server-ingest.rst, releasenotes/releasenotes_v5.rst, setting_up_firely_server/configuration/appsettings.rst
Added release note on Vonk-5014
=> Added release note on Vonk-5014

features_and_tools/firely-server-ingest.rst
=> VONK-5552: FSI 2.3.0 release notes draft

features_and_tools/firely-server-ingest.rst, features_and_tools/pubsub.rst
Note: Wait until pubsub sample repo is public before merging
=> Adding documentation: clients for pubsub API (+ fixing format error)

security/firely-auth/firely-auth-releasenotes.rst, security/firely-auth/firely-auth-settings.rst
- Added release nodes for Firely Auth 3.3.0-rc3
- Add documents about new settings
=> Release nodes for Firely Auth 3.3.0-rc3

setting_up_firely_server/configuration/sqlserver/disk_configuration.rst
I took all my "organized" disk/file based performance notes and added them to our doc. I have others but this is a good start.
Implements VONK-6571
=> update bp doc

setting_up_firely_server/configuration/environment_variables.rst
=> fix: revisit envvar

features_and_tools/custom_operations/customoperations.rst, features_and_tools/custom_operations/member-match.rst, releasenotes/releasenotes.rst, releasenotes/releasenotes_v6.rst, setting_up_firely_server/configuration/plugins/available_plugins.rst
DRAFT PR, since this is in preparation for FS 6 and not to be included in 5.7.
=> feature: $member-match

setting_up_firely_server/configuration/logsettings.rst
=> Improve doc for AWS Cloudwatch sink

security/firely-auth/firely-auth-endpoints.rst
mostly copy/paste from the FS documentation
=> liveness and readiness endpoints

features_and_tools/custom_operations/documentoperation.rst, features_and_tools/restful_api.rst, security/smart.rst, setting_up_firely_server/configuration/appsettings.rst
added the earlier changes to the 5.10.1 branch this time
=> Feature/vonk 8059 on 5.11 (VONK-8059)

security/firely-auth/firely-auth-releasenotes.rst, security/firely-auth/firely-auth-settings.rst
- Added information on recommended favicon dimmensions
- Added information on AllowedOperationScopes
- Updated client settings to match with default appsettings
- Updated release notes
=> VONK-8106, VONK-7894

security/firely-auth/firely-auth-deploy.rst, security/firely-auth/firely-auth-endpoints.rst, security/firely-auth/firely-auth-releasenotes.rst, security/firely-auth/firely-auth-settings.rst
VONK-8151 proxy header settings, VONK-7957 Security headers
=> VONK-8151 proxy header settings, VONK-7957 Security headers

releasenotes/releasenotes_v5.rst
@cheng13231 Please add the release date once you are ready
=> Add release notes for FS v5.11.1

setting_up_firely_server/deployment/reverseproxy/reverseProxy.rst
=> vonk-8521 added AllowAnyNetworkOrigins setting documentation

releasenotes/releasenotes_v6.rst
Wait a bit with merging, we still need to kick off the release pipeline.
=> added release notes FS 6.4 + tag
